### ISSUE TITLE
Wrap EOFError as a dbus error

### ISSUE THREAD

**Issue by bdraco** [Bluetooth-Devices/dbus-fast#19]
Happens on connection drop/close

```
Logger: homeassistant.config_entries
Source: components/homekit_controller/connection.py:198
First occurred: 8:53:38 PM (1 occurrences)
Last logged: 8:53:38 PM

Error setting up entry VOCOlinc-VS1-185620 for homekit_controller
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 365, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/homekit_controller/__init__.py", line 41, in async_setup_entry
    await conn.async_setup()
  File "/usr/src/homeassistant/homeassistant/components/homekit_controller/connection.py", line 198, in async_setup
    await self.pairing.async_populate_accessories_state(force_update=True)
  File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/ble/pairing.py", line 564, in async_populate_accessories_state
    await self._async_populate_accessories_state(force_update)
  File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/ble/pairing.py", line 111, in _async_wrap
    return await func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/ble/client.py", line 75, in _async_wrap
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/ble/pairing.py", line 576, in _async_populate_accessories_state
    await self._populate_accessories_and_characteristics(force_update)
  File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/ble/pairing.py", line 607, in _populate_accessories_and_characteristics
    await self._async_pair_verify()
  File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/ble/pairing.py", line 387, in _async_pair_verify
    session_id, derive = await drive_pairing_state_machine(
  File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/ble/client.py", line 257, in drive_pairing_state_machine
    decoded = await _pairing_char_write(client, char, iid, request)
  File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/ble/client.py", line 211, in _pairing_char_write
    data = await char_write(client, None, None, handle, iid, next_write)
  File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/ble/client.py", line 194, in char_write
    pdu_status, data = await ble_request(
  File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/ble/client.py", line 99, in ble_request
    await _write_pdu(client, encryption_key, opcode, handle, iid, data, tid)
  File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/ble/client.py", line 126, in _write_pdu
    await client.write_gatt_char(handle, write, True)
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/client.py", line 695, in write_gatt_char
    reply = await self._bus.call(
  File "/usr/local/lib/python3.10/site-packages/dbus_fast/aio/message_bus.py", line 337, in call
    await future
  File "/usr/local/lib/python3.10/site-packages/dbus_fast/aio/message_bus.py", line 404, in _message_reader
    if self._unmarshaller.unmarshall():
  File "/usr/local/lib/python3.10/site-packages/dbus_fast/_private/unmarshaller.py", line 332, in unmarshall
    self._read_header()
  File "/usr/local/lib/python3.10/site-packages/dbus_fast/_private/unmarshaller.py", line 271, in _read_header
    self.read_to_offset(HEADER_SIGNATURE_SIZE)
  File "/usr/local/lib/python3.10/site-packages/dbus_fast/_private/unmarshaller.py", line 174, in read_to_offset
    raise EOFError()
EOFError
```

**Comment by bdraco** [comment]
Actually thinking about this, its probably expected and it should be trapped in bleak

**Comment by bdraco** [comment]
looks like there is already an issue for that https://github.com/hbldh/bleak/issues/409

**Comment by bdraco** [comment]
This really isn't a dbus error.  Its a separate error when the dbus get closed unexpectedly.

Probably should be handled downstream

**Comment by dlech** [comment]
dbus-fast has additional error types besides a d-bus error, it could be worth adding a new one for this that gives a better explanation of what the error actually means and how to recover from it.

**Comment by bdraco** [comment]
I think we could have a named exception that inherits from EOFError that explains the stream disconnected

**Comment by dlech** [comment]
I hit this issue this weekend in Bleak. I also noticed that if you call `bus.call(Message(...))` after the bus socket is disconnected, the call hangs forever. Instead it should raise the same `BusDisconnectedError`.

**Comment by joooeey** [comment]
This error still shows up with bleak 19.5. I also had a spotty connection due to far distance.

<details>
  <summary>Traceback</summary>

```
Traceback (most recent call last):
  File "/home/ifos/connect.py", line 136, in run_in_background                                                                                                                                                                                   task = asyncio.create_task(coro)
  File "/usr/lib/python3.10/asyncio/tasks.py", line 336, in create_task
    loop = events.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ifos/connect.py", line 532, in <module>
    connect.start()
  File "/home/ifos/connect.py", line 160, in start
    dev.connect()
  File "/home/ifos/connect.py", line 206, in connect
    self.task = run_in_background(self.run_forever())
  File "/home/ifos/connect.py", line 138, in run_in_background
    asyncio.run(coro)
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/ifos/connect.py", line 231, in run_forever
    await self.open_bridges()
  File "/home/ifos/connect.py", line 240, in open_bridges
    await bridge.start(self.bleak_client)
  File "/home/ifos/connect.py", line 485, in start
    await client.start_notify(uuid, new_handler)
  File "/home/ifos/.local/lib/python3.10/site-packages/bleak/__init__.py", line 649, in start_notify
    await self._backend.start_notify(characteristic, wrapped_callback, **kwargs)
  File "/home/ifos/.local/lib/python3.10/site-packages/bleak/backends/bluezdbus/client.py", line 877, in start_notify
    reply = await self._bus.call(
  File "/home/ifos/.local/lib/python3.10/site-packages/dbus_fast/aio/message_bus.py", line 371, in call
    await future
  File "src/dbus_fast/aio/message_reader.py", line 24, in dbus_fast.aio.message_reader.build_message_reader._message_reader
  File "src/dbus_fast/_private/unmarshaller.py", line 659, in dbus_fast._private.unmarshaller.Unmarshaller._unmarshall
  File "src/dbus_fast/_private/unmarshaller.py", line 533, in dbus_fast._private.unmarshaller.Unmarshaller._read_header
  File "src/dbus_fast/_private/unmarshaller.py", line 283, in dbus_fast._private.unmarshaller.Unmarshaller._read_to_pos
EOFError
```

</details>

**Comment by dlech** [comment]
>     RuntimeError: no running event loop

This makes me thing the issue is deeper than just wrapping the `EOFError`.

I haven't had a chance to get back to it yet, but I think https://github.com/hbldh/bleak/pull/1100/commits/9472a10f2324caee532c4cfdc7e9381212931e35 could help with the issue (and hopefully avoid the `EOFError` altogether).
