### ISSUE TITLE
Calling BleakScanner.discover raises a repeating error / stack-trace

### ISSUE THREAD

**Issue by vincintz** [Bluetooth-Devices/dbus-fast#224]
**Describe the bug**
I initially raised this [issue in bleak](https://github.com/hbldh/bleak/issues/1389). Calling `BleakScanner.discover` can lead to an infinitely recurring exception trace pointing to dbus-fast code. So far I can only consistently reproduce this in one environment.

I'm trying to determine what's different about this environment, and how to avoid/fix this if it ever occurs again.

**To Reproduce**
Here's the OS and libraries installed on the environment this is reproduced. We also have other environments with the same packages/versions where this does issue does not occur.
  * dbus-fast: 1.91.2
  * bleak version: 0.20.2
  * Python version: 3.8.10
  * Operating System: Ubuntu 20.04.4 LTS
  * BlueZ version: 5.53

The minimum code that raise the exception
```
import asyncio
from bleak import BleakScanner

async def main():
    print("scanning for 5 seconds, please wait...")
    devices = await BleakScanner.discover(timeout=5.0, return_adv=True)
    print(devices)

if __name__ == "__main__":
    asyncio.run(main())
```

Running this code prints this output over and over, until I hit ctr-c.
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/dbus_fast/aio/message_reader.py", line 24, in dbus_fast.aio.message_reader.build_message_reader._message_reader
  File "src/dbus_fast/_private/unmarshaller.py", line 662, in dbus_fast._private.unmarshaller.Unmarshaller._unmarshall
  File "src/dbus_fast/_private/unmarshaller.py", line 536, in dbus_fast._private.unmarshaller.Unmarshaller._read_header
  File "src/dbus_fast/_private/unmarshaller.py", line 284, in dbus_fast._private.unmarshaller.Unmarshaller._read_to_pos
  File "src/dbus_fast/_private/unmarshaller.py", line 253, in dbus_fast._private.unmarshaller.Unmarshaller._read_sock
AttributeError: 'cython_function_or_method' object has no attribute 'recvmsg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "src/dbus_fast/aio/message_reader.py", line 35, in dbus_fast.aio.message_reader.build_message_reader._message_reader
TypeError: 'bool' object is not callable
Exception in callback build_message_reader.<locals>._message_reader()
handle: <Handle build_message_reader.<locals>._message_reader()>
Traceback (most recent call last):
  File "src/dbus_fast/aio/message_reader.py", line 24, in dbus_fast.aio.message_reader.build_message_reader._message_reader
  File "src/dbus_fast/_private/unmarshaller.py", line 662, in dbus_fast._private.unmarshaller.Unmarshaller._unmarshall
  File "src/dbus_fast/_private/unmarshaller.py", line 536, in dbus_fast._private.unmarshaller.Unmarshaller._read_header
  File "src/dbus_fast/_private/unmarshaller.py", line 284, in dbus_fast._private.unmarshaller.Unmarshaller._read_to_pos
  File "src/dbus_fast/_private/unmarshaller.py", line 253, in dbus_fast._private.unmarshaller.Unmarshaller._read_sock
AttributeError: 'cython_function_or_method' object has no attribute 'recvmsg'

During handling of the above exception, another exception occurred:
```

**Additional context**
Testing previous bleak version, this issue is replicable from 0.17.0 onwards, but not on 0.16.0.

**Comment by bdraco** [comment]
Can you reproduce the issue with newer python?

**Comment by bdraco** [comment]
I think you have code from mixed versions installed as `_read_sock` doesn't appear in library in `1.91.2` from a failed pip install

Can you try fulling uninstalling the library and reinstalling it.

Make sure any old files are cleaned out.


```python
src/dbus_fast/_private/unmarshaller.pxd:    cdef _read_sock_with_fds(self, unsigned int pos, unsigned int missing_bytes)
src/dbus_fast/_private/unmarshaller.pxd:    cdef _read_sock_without_fds(self, unsigned int pos)
src/dbus_fast/_private/unmarshaller.py:    def _read_sock_with_fds(self, pos: _int, missing_bytes: _int) -> None:
src/dbus_fast/_private/unmarshaller.py:    def _read_sock_without_fds(self, pos: _int) -> None:
src/dbus_fast/_private/unmarshaller.py:            self._read_sock_with_fds(pos, missing_bytes)
src/dbus_fast/_private/unmarshaller.py:            self._read_sock_without_fds(pos)
```

**Comment by vincintz** [comment]
hi @bdraco thanks for the quick response. I don't have full access to the machine right now, but I will try your suggestions as soon as I can (tomorrow at the latest)

**Comment by vincintz** [comment]
hi @bdraco I confirmed that cleaning up the packages fixed the problem. Sorry for raising this here without checking that first.
This issue can now be closed. Thanks again for the quick response and resolution
